## **Pandas_Condition Notebook**

In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\HP\Downloads\titanic_dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [3]:
# Coding
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### **Syntax for loc** 
**df.loc[row_condition, column_selection]**

### Accessing Age above 30:

In [4]:
# Coding
df[df["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

### Using .loc

In [6]:
# Coding 
df.loc[df["Age"]>30, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

### Access data to find a Passengers who has survived

In [8]:
# Coding 
df.loc[df["Survived"]==1, ["Name", "Age", "Survived"]]

                                                   Name   Age  Survived
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                                Heikkinen, Miss. Laina  26.0         1
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                   Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
...                                                 ...   ...       ...
1300                          Peacock, Miss. Treasteall   3.0         1
1301                             Naughton, Miss. Hannah   NaN         1
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0         1
1303                     Henriksson, Miss. Jenny Lovisa  28.0         1
1305                       Oliva y Ocana, Dona. Fermina  39.0         1

[494 rows x 3 columns]

### Access data to find Passenger who are in first Class

In [9]:
# Coding 
df.loc[df["Pclass"]==1, ["Name", "Age", "Sex", "Pclass"]]

                                                   Name   Age     Sex  Pclass
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female       1
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female       1
6                               McCarthy, Mr. Timothy J  54.0    male       1
11                             Bonnell, Miss. Elizabeth  58.0  female       1
23                         Sloper, Mr. William Thompson  28.0    male       1
...                                                 ...   ...     ...     ...
1294                             Carrau, Mr. Jose Pedro  17.0    male       1
1295                       Frauenthal, Mr. Isaac Gerald  43.0    male       1
1298                         Widener, Mr. George Dunton  50.0    male       1
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0  female       1
1305                       Oliva y Ocana, Dona. Fermina  39.0  female       1

[323 rows x 4 columns]

### Accessing data using **and condition**:

### Q.1 Find out a Passenger data who are above age of 30 and has survived

In [1]:
# Caoding 
df.loc[(df["Age"]>30) & (df["Survived"]==1), :]

NameError: name 'df' is not defined

### Q.2 Find out a Passenger data whose age is above 18 or must be Female Passenger

In [18]:
# Coding
df.loc[(df["Age"]>25) | (df["Sex"]=="female"), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

### Q.3 Find out a data of Passenger who are in 3-class and is female

In [20]:
# Coding
df.loc[(df["Pclass"]==3) & (df["Sex"]== "female"), ["Name", "Age", "Pclass"]]

                                                   Name   Age  Pclass
2                                Heikkinen, Miss. Laina  26.0       3
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3
10                      Sandstrom, Miss. Marguerite Rut   4.0       3
14                 Vestrom, Miss. Hulda Amanda Adolfina  14.0       3
18    Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0       3
...                                                 ...   ...     ...
1274                McNamee, Mrs. Neal (Eileen O'Leary)  19.0       3
1299                    Riordan, Miss. Johanna Hannah""   NaN       3
1300                          Peacock, Miss. Treasteall   3.0       3
1301                             Naughton, Miss. Hannah   NaN       3
1303                     Henriksson, Miss. Jenny Lovisa  28.0       3

[216 rows x 3 columns]

### Q.4 Find out a data of Passenger who are in 3-class and is male

In [22]:
# Coding 
df.loc[(df["Pclass"]==3) & (df["Sex"]=="male"), ["Name", "Age", "Pclass"]]

                                Name   Age  Pclass
0            Braund, Mr. Owen Harris  22.0       3
4           Allen, Mr. William Henry  35.0       3
5                   Moran, Mr. James   NaN       3
7     Palsson, Master. Gosta Leonard   2.0       3
12    Saundercock, Mr. William Henry  20.0       3
...                              ...   ...     ...
1290        Conlon, Mr. Thomas Henry  31.0       3
1304              Spector, Mr. Woolf   NaN       3
1306    Saether, Mr. Simon Sivertsen  38.5       3
1307             Ware, Mr. Frederick   NaN       3
1308        Peter, Master. Michael J   NaN       3

[493 rows x 3 columns]

### Q.5 Find out the data of female Passenger who are olde than 25

In [24]:
# Coding 
df.loc[(df["Age"]>25) & (df["Sex"]== "female"), ["Name", "Age", "Sex"]]

                                                   Name   Age     Sex
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                                Heikkinen, Miss. Laina  26.0  female
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
11                             Bonnell, Miss. Elizabeth  58.0  female
...                                                 ...   ...     ...
1288  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...  48.0  female
1291                            Bonnell, Miss. Caroline  30.0  female
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0  female
1303                     Henriksson, Miss. Jenny Lovisa  28.0  female
1305                       Oliva y Ocana, Dona. Fermina  39.0  female

[210 rows x 3 columns]

### Q.6 Find out the average age of Survival

In [25]:
# Coding
df.loc[df["Survived"]==1, "Age"].mean()

28.93107913669065

### Q.7 Find out the data of Rich passengers (Fare > 100) who survived, only find name and age

In [ ]:
# Coding
df.loc[(df["Fare"]>100) & (df["Survived"]==1), ["Name", "Age", "Fare"]]

                                                Name   Age      Fare
27                    Fortune, Mr. Charles Alexander  19.0  263.0000
31    Spencer, Mrs. William Augustus (Marie Eugenie)   NaN  146.5208
88                        Fortune, Miss. Mabel Helen  23.0  263.0000
118                         Baxter, Mr. Quigg Edmond  24.0  247.5208
195                             Lurette, Miss. Elise  58.0  146.5208
...                                              ...   ...       ...
1262                       Wilson, Miss. Helen Alice  31.0  134.5000
1266                        Bowen, Miss. Grace Scott  45.0  262.3750
1291                         Bonnell, Miss. Caroline  30.0  164.8667
1298                      Widener, Mr. George Dunton  50.0  211.5000
1305                    Oliva y Ocana, Dona. Fermina  39.0  108.9000

[84 rows x 3 columns]

### Q.8 Find out the data of the name and age of Children (<15) in 3rd class

In [28]:
# Coding
df.loc[(df["Age"]<15) & (df["Pclass"]==3), ["Name", "Age"]]

                                      Name   Age
7           Palsson, Master. Gosta Leonard   2.0
10         Sandstrom, Miss. Marguerite Rut   4.0
14    Vestrom, Miss. Hulda Amanda Adolfina  14.0
16                    Rice, Master. Eugene   2.0
24           Palsson, Miss. Torborg Danira   8.0
...                                    ...   ...
1251           Sage, Master. William Henry  14.5
1270           Asplund, Master. Carl Edgar   5.0
1280           Palsson, Master. Paul Folke   6.0
1283         Abbott, Master. Eugene Joseph  13.0
1300             Peacock, Miss. Treasteall   3.0

[75 rows x 2 columns]

### Q.9 Count passengers older than 60

In [30]:
# Coding
df.loc[df["Age"]>60, :].shape[0]

33